on:
  push:
    branches:
      - master

jobs:
  deploy-to-lightning:
    runs-on: ubuntu-latest
    name: A job to deploy to Lightning
    permissions:
      contents: write
    steps:
      - name: openfn deploy
        uses: openfn/cli-deploy-action@v1.0.0
        with:
          secret_input: ${{ secrets.OPENFN_4b31fe8d_913a_402e_ad04_f8f36befaaf5_API_KEY }}
          config_path_input: 'openfn-4b31fe8d-913a-402e-ad04-f8f36befaaf5-config.json'
